    // Add current state calculations
    AddIsResolved = Table.AddColumn(AddSLOAchievement3, "IsResolved", each [resolution_date] <> null),
    
    // Add ResolutionTimeDays calculated column
    AddResolutionTimeDays = Table.AddColumn(AddIsResolved, "ResolutionTimeDays", each
        if [resolution_date] <> null then
            Duration.Days([resolution_date] - [created])
        else null
    ),
    
    // Add Met_SLA calculated column
    AddMetSLA = Table.AddColumn(AddResolutionTimeDays, "Met_SLA", each
        if [ResolutionTimeDays] <> null and [ResponseTimeTargetDays] <> null then
            [ResolutionTimeDays] <= [ResponseTimeTargetDays]
        else null
    ),
    
    AddIsOverdue = Table.AddColumn(AddMetSLA, "IsOverdue", each
        if [ResponseTimeTargetDays] <> null and [resolution_date] = null then
            [TotalResponseTimeHours] > ([ResponseTimeTargetDays] * 24)
        else false
    ),